#!/bin/bash

output="comments.json"
url="https://blender.meta.stackexchange.com/questions/622/pre-canned-comments-to-help-users/"

html_content=$(curl -s "$url")

notice="This file was autogenerated by $0 and should not be edited manually"
echo "{" > $output
echo "  \"AUTOGENERATE_NOTICE\": \"$notice\"," >> $output
echo "  \"SOURCE:\":\"https://blender.meta.stackexchange.com/questions/622/pre-canned-comments-to-help-users/\"," >> $output
echo "  \"______:\":\"\"," >> $output

extract_section() {
    local section_name="$1"
    local header="$2"
    local in_section=0
    local first_item_in_section=1

    if [ "$first_section" -eq 0 ]; then
        echo "," >> $output
    else
        first_section=0
    fi

    echo "  \"$section_name\": [" >> $output

    while IFS= read -r line; do
        if [[ "$line" =~ ^\<h2\> ]]; then
            if [[ "$line" == *"$header"* ]]; then
                in_section=1
            else
                in_section=0
            fi
            continue
        fi

        if [ "$in_section" -eq 1 ]; then
            if [[ "$line" =~ ^\<h3\> ]]; then
                if [ "$first_item_in_section" -eq 0 ]; then
                    printf ",\n" >> $output
                fi
                title=$(echo "$line" | sed -e 's/<\/\?h3>//g' -e 's/^[ \t]*//')
                read -r description
                description=$(echo "$description" | sed -e 's/<\/\?code>//g' -e 's/<\/\?p>//g' -e 's/^[ \t]*//')
                printf "    {\n" >> $output
                printf "      \"title\": \"%s\",\n" "$title" >> $output
                printf "      \"description\": \"%s\"\n" "$description" >> $output
                printf "    }" >> $output
                first_item_in_section=0
            fi
        fi
    done <<< "$html_content"

    echo -e "\n  ]" >> $output
}

first_section=1

extract_section "questions" "Questions"
extract_section "answers" "Answers"
extract_section "miscellaneous" "Misc"
extract_section "others" "Others"

echo "}" >> $output
jq . "$output" > temp.json && mv temp.json "$output"

echo "Generated pre-canned comments file: $output"
